// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HomeController from "./home_controller"
application.register("home", HomeController)

import AboutController from "./about_controller"
application.register("about", AboutController)

import AdminController from "./admin_controller"
application.register("admin", AdminController)
